(defun c-vl-occur ()
  (interactive)
  (when (string= buffer-file-name v-vl-log-file)
    (save-excursion
      (end-of-line)
      (when (re-search-backward "\\[\\[d:/.*\\]\\]" nil t)
	(let* ((link (buffer-substring (match-beginning 0) (match-end 0)))
	       (link-re (regexp-quote link)))
	  (f-vl-trim link-re)
	  (align-regexp 3 (point-max) "\\.[0-9]+\\( +\\)\\* \\[\\[" nil 4)
	  (f-vl-occur link-re))))))

(defun c-vl-update (&optional folder)
  (interactive)
  (let* ((link (concat "[[" (or folder buffer-file-name) "]]"))
	 (link-re (regexp-quote link))
	 (modtime (if folder (current-time) (visited-file-modtime))))
    (unless (eq modtime 0)
      (find-file-other-window v-vl-log-file)
      (visual-mode)
      (org-remove-occur-highlights nil nil t)
      (goto-char 3) (org-content)
      (let* ((date (format-time-string "%y-%m-%d %H:%M" modtime))
	     (old (and (re-search-forward link-re nil t)
		       (re-search-backward "[0-9]+\\.[0-9]+" nil t)
		       (buffer-substring (match-beginning 0) (match-end 0))))
	     (temp (f-vl-occur link-re))
	     (prompt (concat (when old (concat "Last version: " old ". ")) "New version: "))
	     (new (read-string prompt)))
	(goto-char 3) (org-content)
	(call-interactively 'org-insert-subheading)
	(insert (concat date (make-string 4 ?\s) new " * " link))
	(f-vl-trim link-re)
	(align-regexp 3 (point-max) "\\.[0-9]+\\( +\\)\\* \\[\\[" nil 4)))))

(defun c-vl-update-folder ()
  (interactive)
  (c-vl-update default-directory))

(defun f-vl-occur (re &optional bg ed)
  (let ((para org-occur-parameters))
    (org-remove-occur-highlights nil nil t)
    (if para (org-content)
      (push re org-occur-parameters)
      (save-excursion
	(goto-char 3)
	(org-overview)
	(while (re-search-forward re nil t)
	  (org-highlight-new-match
	   (+ (or bg 0) (match-beginning 0))
	   (+ (or ed 0) (match-end 0)))
	  (org-show-context 'occur-tree)))
      (org-add-hook 'before-change-functions
		    'org-remove-occur-highlights nil 'local)
      (recenter))))

(defun f-vl-trim (re)
  (let ((pt (point)))
    (goto-char (point-max))
    (while (and (> (how-many re 3 (point)) 5)
		(re-search-backward re nil t))
      (message "Record killed: %s"
	       (buffer-substring (line-beginning-position) (line-end-position)))
      (kill-whole-line))
    (goto-char pt)))

(defvar v-vl-log-file (concat v-default-dir "..org"))
